name: hummit
description: "The Gemini song-writing assistant"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.0

dependencies:
    flutter:
        sdk: flutter
    google_fonts: ^6.2.1
    record: ^4.0.0
    http: ^1.0.0
    path_provider: ^2.0.15
    google_generative_ai: ^0.4.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    flutter_launcher_icons: ^0.10.0

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/icons/

flutter_icons:
    android: true
    ios: true
    image_path: "assets/hummit_logo.png" # Path to your custom app icon
